name: Update

on:
  schedule:
    # Esegue ogni 2 ore al minuto 30 (es. 00:30, 02:30, 04:30...)
    # Garantisce il rinnovo prima della scadenza delle 3 ore.
    - cron: '30 */2 * * *'
  push:
    branches:
      - main
  workflow_dispatch: # Permette di avviarlo manualmente dalla tab Actions

jobs:
  update-links:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permesso necessario per fare il push dei file aggiornati
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run update script
        run: python meow.py

      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add sanm_tv.m3u8 sanm_sport.m3u8
          
          # Esegue il commit solo se i file sono effettivamente cambiati
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update" && git push)
